teleop_twist_joy_node:
  ros__parameters:
    axis_linear:
      x: 3
    scale_linear:
      x: 10.0
    scale_linear_turbo:
      x: 1.5

    axis_angular:
      yaw: 2
    scale_angular:
      yaw: 0.40

    enable_button: 5  # L2 shoulder button
    enable_turbo_button: 4  # L1 shoulder button
    require_enable_button: false
