crop_type: orange_tree_natroon
plant_spacing_min: 4.0
plant_spacing_max: 4.1
row_width: 6.0
row_segments:
  - straight
ground_resolution: 0.5
hole_size: 0
hole_prob: 0.0
ground_ditch_depth: 0.0001
ground_elevation_max: 0.0001

